server:
  port: 8002

spring:
  application:
    name: cloud-payment-service #微服务的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver         #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ccl123456


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.ccl.springcloud.entities    #所有Entities别名类所在的包路径

eureka:
  client:
    register-with-eureka: true    #表示是否将自己注册进EurekaService 默认为true
    fetch-registry: true          #是否从EurekaService抓取自己的注册信息，默认为true，单节点无所谓，集群必须设置为true才能；配合ribbon是否负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: payment8002  #配置主机名称
    prefer-ip-address: true  #访问路径可以显示Ip地址
